---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-service-secret
  namespace: popolitics
spec:
  encryptedData:
    DB_PASSWORD: AgCNSWTPRxurll9cVkxlTZyvAITbPx2ef7L2zgKn/TUbcwYM9eVUi6LkdBwaEx7i18wndRKUQGvBqUZZXU8T87r4zPtXysxHg9/jaWMApsQVY/duehiBr/T9s8ZMRdmWbX4gxvfFON4s8lixJ+n5i38uy4ubEfijT9bMjBbjAOwflp6lJHSwWEmhUCvs90xPXxLvS4SOD1/k7nJFufAPJYqxQrPX62R3oxBVSfgBoj8QWMFmsurhH+Asc61wo0VZ3FhZzTo36VvSpEX0t+Pse5wb+pA9TZQ9MVGDkks6zJV+d2caROI40+9uoX7kWSUvStP2FAD8v1LHPhaTkv7ibKG0Km6wX/8AiqZGN6+sqgjhVAI5qF1oygx0f9OYOw38+xtUuMt+fke+zpH/qw1qi/QO5FTPjvWH81X9qRHpTlYAXnq5jvFiGMmTcIU4f/Dp9/3nx7VlZhJ53WDZDyTRm9VLq4ZzlgazwB4xlxf/UwEF6qq+DnKksewxQaTbVvwUDT4oxuhKeNQu577slRLAa1M9I4rridmO7pz9J+UEI9eEJuW6KkQpA15wUUxTYI81PId8isbPjzlJbg0k/mcC785FDjsfO5mNbMEto3JAhUmr8Bq4p9+TYC+2tCPr6kUak3ulwd7NM3MUsPQyDQRGVtTE1IRbtj7Hv61x2tK+Sc28C5rfUQdV75v9J3rOOch3FmcWfmdBTXhxo0+V
    DJANGO_SECRET_KEY: AgCMlLCSOwbOVzRRRqI1eM7b02pUp3esSIF0A+tQYnsjM2hEMzUqtCCnkk1l/bxirczQK3Y+7//NnqFyAeTVg7ZM+Q3xnEJnLSNswYga7uK/eOuvLRlH6OJEPwB2C2v305Fc8QMlW1AQv9VVLEtB5eKJ/aowfw6XN5M9qrGimBKWU0bLVrOjCrU11HNU29IxN3KOHiVcIW6I2py6VrXyDxc/C9fZNzSZ6MZfBdDmcXXThw+ad0Z4wqRMaX1t3R6vQACSLvfKW3gHNKMtw8zth8mFZM8dt+T1OqGESWc3J7TG9IBiCyBwvZvZfdgdfbLKYN6Hb/c1/yZMeIS8xwHfKsoTsfTjb/DfFnvELLWOAid1Twu98RsKDGWFyPNtFTrjaBvS38Lv553bLGOheLNf+AH0MD2YiAq0WWU0uXKHtVNioVrEAN0AgQuM1uMcHwGWqRyfbYcHoHuED5Kyo62zjppD8TmA1FEPA7yFi5QFfLZptz+B6W3pO71ShbGFpAaUrDE037JXJvCgqzB3Xma/8PM5EdLdres9T89o6L47NXn6IssqAfDsIV2MNWs7KGwp4i4A3zLtgqdmuKu3NiEiVbEKEs3xDaY30SjZpo3J9fiENELWUvcmqDwWY64+aEjjsSJ2r+uNNqUT3N8RMzXZ8Q3ORFHWngFV4feDgI479aV2AAYlvfV7miRdXEI3my5qQv4GS1znwUXDGQX/cQoCU5qrDO4Tmr4NY9i9pMu+qw==
  template:
    metadata:
      creationTimestamp: null
      name: auth-service-secret
      namespace: popolitics
    type: Opaque
