apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: popolitics-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Popolitics/infra.git'
    targetRevision: feat/AUTH-1-init-argocd-integration-and-auth-service
    path: k8s/base/ingress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: popolitics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true