# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - auth_service_base/pvc.yaml
  - auth_service_base/deployment.yaml
  - auth_service_base/service.yaml
  - auth_service/secret.yaml
  - auth_service/service.yaml
  - auth_service/deployment.yaml